version: "3"

services:
  app-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/usr/src/app-dir/app
    ports:
      - "4000:4000"
    environment:
      REDIS_URL: redis://redis-server:6379
      PORT: 4000
    depends_on:
      - redis-server
  redis-server:
    image: "redis:alpine"