name: test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: "20.13.1"
      - name: Install npm packages
        run: npm ci
      - name: Install redis-server
        run:
          sudo apt-get update
          sudo apt-get install -y redis-server
      - name: Start redis-server
        run: redis-server --daemonize yes --requirepass test_env --port 6380
      - name: Run test
        run: npm run test
      - name: test build
        run: npm run build